USE adlister_db;
DROP TABLE IF EXISTS ads;
CREATE TABLE ads(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
title VARCHAR(50) NOT NULL,
description VARCHAR(100),
user_id INT NOT NULL,
PRIMARY KEY(id)
);

SELECT * FROM ads;